### ISSUE TITLE
indy.error.IndyError: ErrorCode.CommonInvalidState

### ISSUE THREAD

**Issue by mehmetaydar** [bcgov/permitify#105] opened 2018-09-17 13:46 UTC
I am following the quick start guide (https://github.com/bcgov/TheOrgBook/blob/master/docker/README.md#running-a-complete-provisional-von-network). I am receiving the following error (indy.error.IndyError: ErrorCode.CommonInvalidState) while starting the permitify. Below is the output:

> bc@FRA1000013983:~/blockchain/indy/bcgov/permitify/docker$ ./manage start seed=issuer_service_00000000000000000 TOB_INDY_SEED=the_org_book_0000000000000000000
WARNING: The RUST_BACKTRACE variable is not set. Defaulting to a blank string.
permitify_redis_1 is up-to-date
Creating permitify_bc_registries_1 ...
Creating permitify_bc_registries_1 ... done
Attaching to permitify_bc_registries_1
bc_registries_1                        | ==================================================================================
bc_registries_1                        | Initializing issuer service.
bc_registries_1                        | ----------------------------------------------------------------------------------
bc_registries_1                        |
bc_registries_1                        | TEMPLATE_NAME: bc_registries
bc_registries_1                        | INDY_WALLET_SEED: issuer_service_00000000000000001
bc_registries_1                        | INDY_WALLET_TYPE: virtual
bc_registries_1                        | WEB_CONCURRENCY: 1
bc_registries_1                        | DEBUG:
bc_registries_1                        | Cmd: /usr/libexec/s2i/s2i_run
bc_registries_1                        | ==================================================================================
bc_registries_1                        |
bc_registries_1                        | Copying template directory; /home/indy/site_templates/bc_registries ...
bc_registries_1                        |
bc_registries_1                        | Starting server ...
bc_registries_1                        |
bc_registries_1                        | ---> Serving application with gunicorn (wsgi) ...
bc_registries_1                        | [2018-09-17 13:40:39 +0000] [1] [INFO] Starting gunicorn 19.7.1
bc_registries_1                        | [2018-09-17 13:40:39 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
bc_registries_1                        | [2018-09-17 13:40:39 +0000] [1] [INFO] Using worker: sync
bc_registries_1                        | [2018-09-17 13:40:39 +0000] [78] [INFO] Booting worker with pid: 78
bc_registries_1                        | ERROR 2018-09-17 13:40:40,319 apps 78 139664008779520 startup code ...
bc_registries_1                        | DEBUG 2018-09-17 13:40:40,323 apps 78 139664008779520 running ...
bc_registries_1                        | DEBUG 2018-09-17 13:40:40,323 apps 78 139664008779520 running in run ...
bc_registries_1                        | DEBUG 2018-09-17 13:40:40,323 agent 78 139664008779520 Issuer __init__>>>
bc_registries_1                        | INFO 2018-09-17 13:40:40,323 genesis 78 139664008779520 Using genesis transaction file from http://10.206.61.105:9000/genesis ...
bc_registries_1                        | INFO 2018-09-17 13:40:40,328 genesis 78 139664008779520 Writing genesis transaction file to, /home/indy/genesis ...
bc_registries_1                        | DEBUG 2018-09-17 13:40:40,330 agent 78 139664008779520 Using virtual Cfg: {'freshness_time': 0} Creds: {'key': '', 'virtual_wallet': None}
bc_registries_1                        | DEBUG 2018-09-17 13:40:40,330 agent 78 139664008779520 Issuer __init__>>> create wallet virtual {'freshness_time': 0} {'key': '', 'virtual_wallet': None}
bc_registries_1                        | DEBUG 2018-09-17 13:40:40,330 agent 78 139664008779520 Issuer __init__>>> done virtual {'freshness_time': 0} {'key': '', 'virtual_wallet': None}
bc_registries_1                        | DEBUG 2018-09-17 13:40:40,330 agent 78 139664008779520 Issuer __init__>>> created VonIssuer
bc_registries_1                        | DEBUG 2018-09-17 13:40:40,330 agent 78 139664008779520 Issuer __aenter__>>>
bc_registries_1                        | INFO 2018-09-17 13:40:40,330 agent 78 139664008779520
bc_registries_1                        |
bc_registries_1                        |
bc_registries_1                        | ==========await self.pool.open()==========
bc_registries_1                        |
bc_registries_1                        |
bc_registries_1                        |
bc_registries_1                        |  INFO|command_executor              |                src/commands/mod.rs:68  | Worker thread started
bc_registries_1                        |  INFO|indy::commands                |                src/commands/mod.rs:99  | PoolCommand command received
bc_registries_1                        |  INFO|pool_command_executor         |               src/commands/pool.rs:56  | Create command received
bc_registries_1                        |  INFO|indy::commands                |                src/commands/mod.rs:99  | PoolCommand command received
bc_registries_1                        |  INFO|pool_command_executor         |               src/commands/pool.rs:64  | Open command received
bc_registries_1                        | DEBUG|zmq                           |/home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.2/src/lib.rs:410 | context dropped
bc_registries_1                        | ERROR|indy::services::pool          |           src/services/pool/mod.rs:426 | Pool worker thread finished with error CommonError(InvalidState("MerkleTree contains invalid data Syntax(\"missing field `data`\")"))
bc_registries_1                        |  INFO|indy::commands                |                src/commands/mod.rs:99  | PoolCommand command received
bc_registries_1                        | DEBUG|zmq                           |/home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/zmq-0.8.2/src/lib.rs:503 | socket dropped
bc_registries_1                        |  INFO|indy::commands::pool          |               src/commands/pool.rs:68  | OpenAck handle 1, pool_id 2, result Err(CommonError(InvalidState("MerkleTree contains invalid data Syntax(\"missing field `data`\")")))
bc_registries_1                        | ERROR|indy::errors::indy            |                 src/errors/indy.rs:72  | Casting error to ErrorCode: Invalid library state: MerkleTree contains invalid data Syntax("missing field `data`")
bc_registries_1                        | ERROR|indy::errors::indy            |                 src/errors/indy.rs:74  | Backtrace: stack backtrace:
bc_registries_1                        |    0:     0x7f06071c1cec - backtrace::backtrace::trace::hc0a4868e3bd2cdd4
bc_registries_1                        |    1:     0x7f06071bea22 - backtrace::capture::Backtrace::new::he25e1ff8089ac60f
bc_registries_1                        |    2:     0x7f0606db889a - <indy::errors::indy::IndyError as indy::errors::ToErrorCode>::to_error_code::hd9d063cbf277f48c
bc_registries_1                        |    3:     0x7f0606dfe278 - indy::api::pool::indy_open_pool_ledger::{{closure}}::h7880ff50eecf7671
bc_registries_1                        |    4:     0x7f0606c3e724 - indy::commands::pool::PoolCommandExecutor::execute::hbb366030b2f70f96
bc_registries_1                        |    5:     0x7f0606dc5684 - std::sys_common::backtrace::__rust_begin_short_backtrace::h15a1dedfd882ab72
bc_registries_1                        |    6:     0x7f0606c320c2 - std::panicking::try::do_call::h0b12810d744f34f6
bc_registries_1                        |    7:     0x7f0607454c4e - __rust_maybe_catch_panic
bc_registries_1                        |                         at libpanic_unwind/lib.rs:102
bc_registries_1                        |    8:     0x7f0606dcf939 - <F as alloc::boxed::FnBox<A>>::call_box::h8c0ad5d1fa7772ac
bc_registries_1                        |    9:     0x7f060744bd77 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h3a46ab40d44ff8db
bc_registries_1                        |                         at /checkout/src/liballoc/boxed.rs:794
bc_registries_1                        |                          - std::sys_common::thread::start_thread::heca3dbba8ff4f46a
bc_registries_1                        |                         at libstd/sys_common/thread.rs:24
bc_registries_1                        |   10:     0x7f060741ae38 - std::sys::unix::thread::Thread::new::thread_start::ha1ecaaa6d3efa77d
bc_registries_1                        |                         at libstd/sys/unix/thread.rs:90
bc_registries_1                        |   11:     0x7f060f5e56b9 - start_thread
bc_registries_1                        |   12:     0x7f060ec0b41c - clone
bc_registries_1                        |   13:                0x0 - <unknown>
bc_registries_1                        | WARNING 2018-09-17 13:40:40,363 libindy 78 139664008779520 _indy_loop_callback: Function returned error 112
bc_registries_1                        | [2018-09-17 13:40:40 +0000] [78] [ERROR] Exception in worker process
bc_registries_1                        | Traceback (most recent call last):
bc_registries_1                        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
bc_registries_1                        |     worker.init_process()
bc_registries_1                        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
bc_registries_1                        |     self.load_wsgi()
bc_registries_1                        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
bc_registries_1                        |     self.wsgi = self.app.wsgi()
bc_registries_1                        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
bc_registries_1                        |     self.callable = self.load()
bc_registries_1                        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
bc_registries_1                        |     return self.load_wsgiapp()
bc_registries_1                        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
bc_registries_1                        |     return util.import_app(self.app_uri)
bc_registries_1                        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
bc_registries_1                        |     __import__(module)
bc_registries_1                        |   File "/home/indy/wsgi.py", line 16, in <module>
bc_registries_1                        |     application = get_wsgi_application()
bc_registries_1                        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
bc_registries_1                        |     django.setup(set_prefix=False)
bc_registries_1                        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
bc_registries_1                        |     apps.populate(settings.INSTALLED_APPS)
bc_registries_1                        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
bc_registries_1                        |     app_config.ready()
bc_registries_1                        |   File "/home/indy/von_connector/apps.py", line 134, in ready
bc_registries_1                        |     issuer_service_id = eventloop.do(run())
bc_registries_1                        |   File "/home/indy/von_connector/eventloop.py", line 24, in do
bc_registries_1                        |     return event_loop.run_until_complete(coro)
bc_registries_1                        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
bc_registries_1                        |     return future.result()
bc_registries_1                        |   File "/home/indy/von_connector/apps.py", line 76, in run
bc_registries_1                        |     async with Issuer() as agent:
bc_registries_1                        |   File "/home/indy/von_connector/agent.py", line 86, in __aenter__
bc_registries_1                        |     await self.pool.open()
bc_registries_1                        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/von_agent/nodepool.py", line 153, in open
bc_registries_1                        |     self._handle = await pool.open_pool_ledger(self.name, json.dumps(self.cfg))
bc_registries_1                        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/indy/pool.py", line 82, in open_pool_ledger
bc_registries_1                        |     open_pool_ledger.cb)
bc_registries_1                        | indy.error.IndyError: ErrorCode.CommonInvalidState
bc_registries_1                        | [2018-09-17 13:40:40 +0000] [78] [INFO] Worker exiting (pid: 78)
bc_registries_1                        | [2018-09-17 13:40:40 +0000] [1] [INFO] Shutting down: Master
bc_registries_1                        | [2018-09-17 13:40:40 +0000] [1] [INFO] Reason: Worker failed to boot.
permitify_bc_registries_1 exited with code 3

>

**Comment by nrempel** [comment] 2018-09-17 18:49
Hi @mehmetaydar,

We recently made some significant changes to permitify.

Can you please ensure that you are running the very latest code from the `master` branch of https://github.com/bcgov/von-network, https://github.com/bcgov/TheOrgBook, and https://github.com/bcgov/permitify?

Once you have the latest code, run `./manage rm` on all 3 of the environment to clean their state.

Once you've done this, you should be able to try running the environments again like you did previously.

Let me know if those steps work for you.

**Comment by swcurran** [comment] 2018-09-21 03:29
FYI - on the permitify instructions - there are two scripts "manage" and "manage.sh".  Use the one "manage.sh" for now - it's the right one.  We'll fix that shortly.

**Comment by mehmetaydar** [comment] 2018-09-21 12:16
I checkout the latest versions from master branch for TheOrgBook, von-network, and permitify. I am receiving the following error while building permitify:

> ./manage.sh build
> 
> Building containers ...
> docker-compose build
> ERROR: Invalid interpolation format for "environment" option in service "liquor-control-agent": "${TOB_APP_URL:-}"

any idea?

**Comment by mehmetaydar** [comment] 2018-09-21 13:20
I checkout the latest versions from master branch for TheOrgBook, von-network, and permitify. I was able to build them. The von-network (http://localhost:9000/ ) and TheOrgBook (http://10.206.61.105:8080) successfuly loads. However there is a confusion on how to start the permitify. @swcurran mentioned that we should use manage.sh under permitify/docker. I used manage.sh to build permitify. However manage.sh does not have registerDids argument. I am following the quick start guide (https://github.com/bcgov/TheOrgBook/blob/master/docker/README.md#running-a-complete-provisional-von-network ) I think the quick start guide needs to be updated.

I have run the following but I am still not able to run permitify:
From .../TheOrgBook/docker run ./manage registerDids seed=the_org_book_0000000000000000000
From .../permitify/docker run ./manage registerDids seed=issuer_service_00000000000000000
From .../permitify/docker `./manage.sh start seed=issuer_service_00000000000000000 TOB_INDY_SEED=the_org_book_0000000000000000000` ('start all' argument not working)
Now, when I run http://localhost:5000 on the browser I get: "404 Site 10.206.61.105:5000 is not served on this interface." And the logs says:

> caddy_1                   | 2018/09/21 13:06:43 [INFO] 10.206.61.105 - No such site at :80 (Remote: 10.122.24.89, Referer: )

Any suggestion?

**Comment by swcurran** [comment] 2018-09-21 15:11
@mehmetaydar - try localhost:5000/demo - That should work.  There is no longer need to specify the seeds, so that's dropped from the script.  Sorry I forgot to mention that in the note earlier. Again - the caddyfile can be updated to address that issue, to that just localhost:5000 works.

**Comment by mehmetaydar** [comment] 2018-09-24 10:47
@swcurran  localhost:5000/demo does not work. I am still getting 

> 404 Site 10.206.61.105:5000 is not served on this interface
and
> caddy_1                   | 2018/09/24 05:38:28 [INFO] 10.206.61.105 - No such site at :80 (Remote: 10.122.24.89, Referer: )

Is it possible that you can provide an updated instructions of the "Quick Start Guide?" I might be missing something. thanks.

**Comment by swcurran** [comment] 2018-09-24 13:30
/demo is still needed to get to the screens. Try that. And yes, I'll get
the getting started guide updated - hopefully today.

**Comment by mehmetaydar** [comment] 2018-09-24 13:58
I have installed them on a server (Ubuntu based virtual machine, no graphical interface). I am accessing it from my windows machine using Chrome. So I don't use localhost:5000/demo. I use http://server-ip:5000/demo. Could that be a problem? The von-network (http://server-ip:9000) and TheOrgBook (http://server-ip:8080) work and they display a screen. However permitify (http://server-ip:5000/demo) does not work.

**Comment by swcurran** [comment] 2018-09-24 14:09
I run it on a Ubuntu server as well and that does work for me, so it's
odd.I ssh into the server as well, using port-forwarding and that works.
Also that when you didn't use the /demo part you got a 404 (Not Found) back
from the server.  I'm on my way to work, so will check when I get there.

**Comment by mehmetaydar** [comment] 2018-09-24 14:35
@swcurran On the Ubuntu server if I run:  `wget http://server-ip:5000` I get  the error: "ERROR 404: Not Found." However, if I run `wget http://localhost:5000` it downloads the page fine and the content of the page says that "If you see this page, Caddy container works." `wget http://localhost:5000/demo` also resolves to another page. So I am starting to think this is either a port forwarding or a proxy issue.

**Comment by swcurran** [comment] 2018-09-24 14:52
I think you are right. The 404 vs. the Caddy message suggests that you are
hitting two different web servers.  Very strange.  :-).

FYI - just started it all up again from scratch and all good.  I'm
portforwarding 9000, 8080 and 5000 for the session.

**Comment by mehmetaydar** [comment] 2018-09-25 06:08
Made it work. I had to explicitly set the `APPLICATION_URL` and `WEB_HOST_NAME` to point to `DOCKERHOST` instead of `localhost` in `permitify/docker/manage` file at the end of the `configureEnvironment` function as below:

` export APPLICATION_URL=${APPLICATION_URL-http://$DOCKERHOST:${WEB_HTTP_PORT:-5000}}`

  `export WEB_HOST_NAME=${DOCKERHOST}`

` echo -e "DOCKERHOST: $DOCKERHOST"`

  `echo -e  "COMPOSE_PROJECT_NAME: $COMPOSE_PROJECT_NAME"`

 `echo -e  "LEDGER_URL: $LEDGER_URL"`

` echo -e "APPLICATION_URL: $APPLICATION_URL"`

  `echo -e "WEB_HOST_NAME: $WEB_HOST_NAME"`


Now the permitify loads.

**Comment by mehmetaydar** [comment] 2018-09-25 07:33
I am able to get to http://server-ip:5000/bcreg/incorporation. When I enter the information and click on the Submit button, it looks like to be working as I get the following output from the logs:

> bcreg-agent_1             | 2018-09-25 07:27:47,209 INFO [vonx.indy.service]: Creating Indy credential offer for issuer bcreg, schema incorporation.permitify
bcreg-agent_1             | 2018-09-25 07:27:47,350 INFO [von_anchor.anchor.base]: _BaseAnchor.get_cred_def: got cred def for 6qnvgJtqwK44D8LFYnV5Yf:3:CL:44:tag from cache
bcreg-agent_1             | 2018-09-25 07:27:48,055 INFO [aiohttp.access]: 172.24.0.8 [25/Sep/2018:07:27:47 +0000] "POST /bcreg/incorporation HTTP/1.1" 200 224 "http://10.206.61.105:5000/bcreg/incorporation" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36"

However, in my experience the demo is not self-explanatory. The instructions are not clear about how to proceed from there. We really need an updated quick-start quide for demo purposes.

**Comment by mehmetaydar** [comment] 2018-09-26 09:10
@swcurran thanks for your inputs. I am able to run the demo, and able to get back to the list of credentials screen. However, I had to set `TOB_APP_URL` and `THE_ORG_BOOK_APP_URL` environment variables in `permitify/docker/manage` file at the end of the `configureEnvironment `function as below:
  `export THE_ORG_BOOK_APP_URL=${TOB_APP_URL}`
  `export WEB_HOST_NAME=${DOCKERHOST}`

The problem I face now is that solr is not working properly. I get the following error when I try to search the business I just registered via TheOrgBook:

> tob-api_1     | Traceback (most recent call last):
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/haystack/backends/solr_backend.py", line 138, in search
tob-api_1     |     raw_results = self.conn.search(query_string, **search_kwargs)
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pysolr.py", line 730, in search
tob-api_1     |     response = self._select(params, handler=search_handler)
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pysolr.py", line 428, in _select
tob-api_1     |     return self._send_request('get', path)
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pysolr.py", line 403, in _send_request
tob-api_1     |     raise SolrError(error_message % (resp.status_code, solr_message))
tob-api_1     | pysolr.SolrError: Solr responded with an error (HTTP 403): [Reason: None]
tob-api_1     | <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head>  <meta http-equiv="X-UA-Compatible" content="IE=7" /><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><meta name="keywords" content="MWG,Proxy" /><title>Corporate Proxy Notification</title>

I believe that is a proxy error. Will try to fix it.

**Comment by mehmetaydar** [comment] 2018-09-26 13:59
In `TheOrgBook/docker/manage` file I have set the following: 

`     ---#export SOLR_SERVICE_NAME="tob-solr"
`  export SOLR_SERVICE_NAME=${DOCKERHOST}`
 ` export SOLR_CORE_NAME=${CORE_NAME}`
  `export SOLR_URL=${http://$SOLR_SERVICE_NAME:8983/solr/$SOLR_CORE_NAME}`

Now I am getting the following error while trying to start TheOrgBook:

> bc@FRA1000013983:~/blockchain/indy/bcgov/TheOrgBook/docker$ ./manage start tob-api seed=the_org_book_0000000000000000000
Creating tob_tob-solr_1  ... done
Creating tob_wallet-db_1 ... done
Creating tob_tob-db_1    ... done
Creating tob_tob-api_1   ... done
Attaching to tob_tob-api_1
tob-api_1     | waiting for solr ...
tob-api_1     | ---> Running application from Python script (app.py) ...
tob-api_1     | Enabling realtime indexing ...
tob-api_1     | Loading custom settings file: custom_settings_bcgov.py
tob-api_1     | INFO 2018-09-26 13:41:51,913 manager 8 140227877299968 Initializing Indy service
tob-api_1     |
tob-api_1     | Migrating database ...
tob-api_1     | Operations to perform:
tob-api_1     |   Apply all migrations: admin, api, api_v2, auth, contenttypes, sessions
tob-api_1     | Running migrations:
tob-api_1     |   No migrations to apply.
tob-api_1     |
tob-api_1     | Search indexing in progress ...
tob-api_1     | INFO 2018-09-26 13:41:52,167 suggest 8 140227877299968 Rebuilding Solr suggester...
tob-api_1     | Traceback (most recent call last):
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/models.py", line 375, in prepare_url
tob-api_1     |     scheme, auth, host, port, path, query, fragment = parse_url(url)
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/urllib3/util/url.py", line 199, in parse_url
tob-api_1     |     raise LocationParseError(url)
tob-api_1     | urllib3.exceptions.LocationParseError: Failed to parse: None:None
tob-api_1     |
tob-api_1     | During handling of the above exception, another exception occurred:
tob-api_1     |
tob-api_1     | Traceback (most recent call last):
tob-api_1     |   File "app.py", line 32, in <module>
tob-api_1     |     run_migration()
tob-api_1     |   File "/home/indy/tob_anchor/boot.py", line 105, in run_migration
tob-api_1     |     call_command("migrate")
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/management/__init__.py", line 131, in call_command
tob-api_1     |     return command.execute(*args, **defaults)
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
tob-api_1     |     output = self.handle(*args, **options)
tob-api_1     |   File "/home/indy/api/management/commands/migrate.py", line 22, in handle
tob-api_1     |     self.__update_search_indexes()
tob-api_1     |   File "/home/indy/api/management/commands/migrate.py", line 35, in __update_search_indexes
tob-api_1     |     SuggestManager().rebuild()
tob-api_1     |   File "/home/indy/api_v2/suggest.py", line 56, in rebuild
tob-api_1     |     'suggest.build': 'true',
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pysolr.py", line 730, in search
tob-api_1     |     response = self._select(params, handler=search_handler)
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pysolr.py", line 428, in _select
tob-api_1     |     return self._send_request('get', path)
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pysolr.py", line 376, in _send_request
tob-api_1     |     timeout=self.timeout, auth=self.auth)
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 525, in get
tob-api_1     |     return self.request('GET', url, **kwargs)
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 498, in request
tob-api_1     |     prep = self.prepare_request(req)
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/sessions.py", line 441, in prepare_request
tob-api_1     |     hooks=merge_hooks(request.hooks, self.hooks),
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/models.py", line 309, in prepare
tob-api_1     |     self.prepare_url(url, params)
tob-api_1     |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/requests/models.py", line 377, in prepare_url
tob-api_1     |     raise InvalidURL(*e.args)
tob-api_1     | requests.exceptions.InvalidURL: Failed to parse: None:None
tob_tob-api_1 exited with code 1

Any suggestion? thanks.

**Comment by mehmetaydar** [comment] 2018-09-27 06:36
It works now. In my case, I had to set the following:
  `export SOLR_SERVICE_NAME=${DOCKERHOST}`
  `export SOLR_CORE_NAME=${CORE_NAME}`
  `export SOLR_URL=${SOLR_URL-http://$SOLR_SERVICE_NAME:8983/solr/$SOLR_CORE_NAME}`
in `TheOrgBook/docker/manage`. I also had to set 
      `- NO_PROXY=${SOLR_SERVICE_NAME}`
      `- no_proxy=${SOLR_SERVICE_NAME}`
      `- SOLR_URL=${SOLR_URL}`
in `TheOrgBook/docker-compose.yml`. I am facing a lot of problems during the installation. I think one of the bottlenecks is that I am working behind a corporate proxy.

**Comment by swcurran** [comment] 2018-09-27 11:41
Awesome.  Sorry I've been offline.  I'm at an identity conference.  We'll
push on this as soon as possible after I'm back.

**Comment by nrempel** [comment] 2018-10-02 20:52
Glad you got it working @mehmetaydar 

I can't seem to reproduce this issue. I believe it is due to your network conditions.

I will close this issue for now but feel free to open a new one if you run into any issues.

**Closed by nrempel** 2018-10-02 20:52 UTC
